//
// Created by dh on 28.10.20.
//

#ifndef TOSTRIPSAPPROXIMATION_GROUNDVERIFIER_H
#define TOSTRIPSAPPROXIMATION_GROUNDVERIFIER_H


class GroundVerifier {

};


#endif //TOSTRIPSAPPROXIMATION_GROUNDVERIFIER_H
